/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "stdlib.h"
#include "string.h"
/* Header for class com_aven_nativesvg_NativeSvgUtils */

#ifndef _Included_com_aven_nativesvg_NativeSvgUtils
#define _Included_com_aven_nativesvg_NativeSvgUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aven_nativesvg_NativeSvgUtils
 * Method:    getNativeBitmap
 * Signature: (Ljava/lang/String;)Landroid/graphics/Bitmap;
 */
JNIEXPORT void JNICALL Java_com_aven_nativesvg_NativeSvgUtils_getNativeBitmap
  (JNIEnv *, jclass, jstring);
#ifdef __cplusplus
}
#endif
#endif
